version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build-and-test:
    docker:
      - image: node:14.17.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v2-{{ .Branch }}-
            - yarn-packages-v2-
      - run:
          name: Dump Cache folder
          command: yarn cache dir
      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      # Run tests
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Unit testing
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/junit
            JEST_JUNIT_OUTPUT_NAME: test-ci-results.xml
      - store_test_results:
          path: /tmp/junit

      # Builds
      - run:
          name: Build
          command: |
            if [[ ${CIRCLE_BRANCH} = develop ]]; then
              yarn build:dev
            elif [[ ${CIRCLE_BRANCH} = release/* ]]; then
              yarn build:prod
            elif [[ ${CIRCLE_BRANCH} = main ]]; then
              yarn build:prod
            fi
      # pass to other jobs
      - persist_to_workspace:
          root: ./
          paths: ./

  # deploy-app:
  #   docker:
  #     - image: circleci/node:12.14.1
  #   steps:
  #     - attach_workspace:
  #         at: ./
  #     - run:
  #         name: Deploy to heroku
  #         command: |
  #           ls -a
  #           echo "Deploying app."
  #           git add ./dist -f
  #           git config user.name ${CIRCLE_USERNAME}
  #           git config user.email $GIT_EMAIL
  #           git commit -m 'Deploy to heroku' --no-verify
  #           # push to heroku git
  #           if [[ ${CIRCLE_BRANCH} = develop ]]; then
  #             git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/t-profile-gen-v2.git HEAD:master
  #           elif [[ ${CIRCLE_BRANCH} = release/* ]]; then
  #             git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/t-profile-gen-v2.git HEAD:master
  #           elif [[ ${CIRCLE_BRANCH} = main ]]; then
  #             git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/t-profile-gen-v2.git HEAD:master
  #           fi
workflows:
  version: 2
  build-all:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
                - /release\/.*/
                - /hotfix\/.*/
    jobs:
      - heroku/deploy-via-git
      # - deploy-app:
      #     requires:
      #       - build-and-test
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - /release\/.*/
      #           - main
